/** Realistic LinkedIn-style articles used to build the 30-page PDF fixture. */
export const ARTICLES = [
  ['Why the LinkedIn Algorithm Rewards Conversation',
    'Most people treat LinkedIn like a broadcast channel. The algorithm does not. It measures how much conversation your post starts, not how many people passively scroll past it. Early comments in the first sixty minutes are the strongest ranking signal you can generate.',
    'Reply to every comment with a question. A reply that ends with a question doubles the chance of a second reply, and every second reply pushes your post into a new network. Dwell time matters too: documents, carousels and long captions keep people on your post longer.'],
  ['The 3-Second Hook',
    'LinkedIn shows the first two lines before the "see more" fold. If those lines do not create curiosity, nothing else you wrote matters. Write the hook last, after you know exactly what the payoff of the post is.',
    'Strong hooks use specificity and tension. "I lost 40% of my audience in one month" beats "growth is hard". Numbers, names and small confessions outperform generic advice. Test three hooks for every idea and keep the one you would stop scrolling for.'],
  ['Posting Cadence That Actually Works',
    'Three to five posts per week is the sweet spot for most creators. Daily posting without a content system burns you out in six weeks, and the algorithm punishes inconsistent quality, not inconsistent quantity.',
    'Batch your writing on one day, schedule across the week, and reserve one slot for a spontaneous post about something that happened that week. Spontaneous posts consistently outperform scheduled ones because they carry genuine energy.'],
  ['Personal Branding Fundamentals',
    'A personal brand is a promise of what you consistently deliver. Your headline, banner and about section should answer three questions in under five seconds: who do you help, how do you help them, and why should I trust you.',
    'Pick one niche and go narrow for the first six months. Broad accounts grow slower because the algorithm cannot figure out who to show your content to. Depth in one topic beats shallow coverage of ten.'],
  ['Storytelling Frameworks That Hold Attention',
    'The most reliable structure is situation, complication, resolution. Start with a moment your reader recognizes, introduce the obstacle that made it hard, then land the lesson you learned. Keep paragraphs under three lines.',
    'White space is a retention tool on LinkedIn. One idea per paragraph, generous line breaks, and a punchy final line. People skim first and read second, so format for the skimmer and reward the reader.'],
  ['Carousel Posts and Documents',
    'Document posts have the highest dwell time of any format. Ten slides, one idea per slide, big text. Slide one is the hook, slides two to eight deliver the promise, slide nine summarizes, slide ten asks for the follow.',
    'Export as PDF, keep the file under ten megabytes, and reuse your best performing articles as carousels. Repurposing is not lazy, it is how one idea reaches four different audiences during the week.'],
  ['Analytics That Actually Matter',
    'Impressions are vanity. The numbers that compound are follower conversion rate, comment depth and profile views per post. If one percent of viewers follow you after a post, that post built an asset, not just noise.',
    'Review analytics every Sunday for twenty minutes. Double down on formats that convert viewers to followers, retire formats that only generate impressions, and log every experiment in a simple spreadsheet.'],
  ['The Commenting Strategy Nobody Talks About',
    'Commenting is posting without the pressure. Twenty thoughtful comments a day on larger accounts in your niche puts your name in front of audiences you could never reach cold. Comments with a point of view get profile visits.',
    'Do not write "great post". Add the missing nuance, share a counterexample, or ask the question everyone is thinking. Spend fifteen minutes on comments before you post, and your own post inherits that warm audience.'],
  ['DMs and the Unscalable Coffee Chat',
    'Every genuine comment on your posts is an invitation for a conversation. Move the best ones to direct messages. Not to sell, but to learn what your audience is actually struggling with this month.',
    'Fifteen short voice notes a week beats any content calendar. Voice notes convert warm followers into believers, and believers comment, share and buy. Community is the moat the algorithm cannot take away.'],
];
