/**
 * Shared domain types for the ingestion pipelines.
 */

/** How a PDF page's text was obtained */
export type ExtractionMethod = 'mupdf' | 'ocr';

/** One extracted PDF page */
export interface PdfPage {
  page: number;
  text: string;
  method: ExtractionMethod;
  charCount: number;
}

export interface PdfExtractionStats {
  totalPages: number;
  textPages: number;
  ocrPages: number;
  totalChars: number;
}

export interface PdfExtractionResult {
  pages: PdfPage[];
  stats: PdfExtractionStats;
}

/** One transcript segment with timestamps (seconds) */
export interface TranscriptSegment {
  startSec: number;
  endSec: number;
  text: string;
}

/**
 * A generic text segment flowing into the chunker. Metadata is merged into
 * every chunk the segment contributes to, so a chunk always knows where it
 * came from (PDF page number, video timestamps, ...).
 */
export interface Segment {
  text: string;
  meta: SegmentMeta;
}

export interface SegmentMeta {
  page?: number;
  /** Last page covered by the chunk when it spans multiple pages */
  pageEnd?: number;
  extraction?: ExtractionMethod;
  startSec?: number;
  endSec?: number;
  [key: string]: unknown;
}

/** A RAG-ready chunk */
export interface Chunk {
  id: string;
  text: string;
  charCount: number;
  meta: SegmentMeta;
}

/** API response for PDF ingestion */
export interface PdfIngestResponse {
  ok: true;
  type: 'pdf';
  fileName: string;
  stats: {
    pages: number;
    ocrUsed: boolean;
    chunks: number;
  };
  chunks: Chunk[];
  /** Number of chunks embedded + stored in the vector DB (RAG layer) */
  indexed: number;
}

/** API response for video/audio ingestion */
export interface MediaIngestResponse {
  ok: true;
  type: 'video';
  fileName: string;
  stats: {
    segments: number;
    durationSec: number;
    chunks: number;
  };
  chunks: Chunk[];
  /** Number of chunks embedded + stored in the vector DB (RAG layer) */
  indexed: number;
}

// ---------------------------------------------------------------------------
// RAG / knowledge layer
// ---------------------------------------------------------------------------

/** One document stored in the vector DB */
export interface VectorDoc {
  id: string;
  /** Original uploaded file this chunk came from */
  source: string;
  text: string;
  meta: SegmentMeta;
  vector: number[];
  indexedAt: string;
}

/** One retrieval hit returned with a RAG answer */
export interface RagSource {
  source: string;
  page?: number;
  pageEnd?: number;
  startSec?: number;
  endSec?: number;
  extraction?: ExtractionMethod;
  score: number;
  snippet: string;
}

/** API response for POST /api/ask */
export interface AskResponse {
  ok: true;
  question: string;
  /** true = generated by the LLM from retrieved context; false = extractive fallback */
  grounded: boolean;
  model: string;
  answer: string;
  sources: RagSource[];
}

// ---------------------------------------------------------------------------
// AI Content Engine — post cards
// ---------------------------------------------------------------------------

/** One interactive quiz question inside a content card */
export interface QuizQuestion {
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}

/**
 * A timeline event inside a carousel card
 * (e.g., "14 JUL - Storming of the Bastille").
 */
export interface CarouselEvent {
  /** Short date / label shown on the left (e.g., "14 JUL", "1793-94") */
  date: string;
  /** Event title (rendered as strong) */
  title: string;
  /** One-sentence description */
  description: string;
  /** When true, the event is marked important (star + highlight styling) */
  important?: boolean;
}

/** A "big event" callout box - contextual explanation at the bottom of a card. */
export interface CarouselBigEvent {
  /** Small caps label, e.g., "WHY IT MATTERS" */
  label: string;
  /** Heading line */
  title: string;
  /** Body paragraph */
  body: string;
}

/** A circular number/stat visual. */
export interface CarouselVisualNumber {
  /** The prominent number / year, e.g., "10" or "1799" */
  value: string;
  /** Caption below the number, e.g., "years of revolution" */
  label: string;
}

/** A summary takeaway box. */
export interface CarouselTakeaway {
  /** Small caps label, e.g., "KEY IDEA" or "FINAL TAKEAWAY" */
  label: string;
  /** Takeaway text */
  text: string;
}

/**
 * A generated content card.
 *
 * Base fields (name, description, keyPoints, quiz) are always present and
 * power the LinkedIn-style grid view.  Optional carousel-* fields are
 * populated when the card was generated in "carousel" format - they map
 * directly to the swipeable carousel UI (category tag, big year/number,
 * timeline events, etc.).
 */
export interface ContentCard {

  id: string;
  /** Uploaded file this card was generated from */
  source: string;
  /** Set on subtopic cards; the topic overview card has no parent */
  parentTopic?: string;
  name: string;
  description: string;
  keyPoints: string[];
  quiz: QuizQuestion[];
  /** "post" (default) or "carousel" (swipeable timeline style) */
  format?: 'post' | 'carousel';
  /** Total number of cards in this set (for the counter, e.g., 5) */
  cardTotal?: number;
  /**
   * true when this card was auto-filled by the LLM to pad out a carousel
   * that had fewer topic cards than needed (Overview / Key Concepts /
   * Timeline / Deep Dive / Summary). Lets the UI show a subtle "✨ AI"
   * badge instead of guessing from ids.
   */
  supplementary?: boolean;

  // ---- carousel format (optional - only when format === 'carousel') ----
  /** Category tag shown top-left, e.g., "FRENCH REVOLUTION" */
  category?: string;
  /** Large display number / year, e.g., "1789" */
  displayNumber?: string;
  /** Heading text */
  heading?: string;
  /** The part of the heading that gets the yellow underline highlight */
  headingHighlight?: string;
  /** Chronological timeline events */
  events?: CarouselEvent[];
  /** Optional contextual callout box */
  bigEvent?: CarouselBigEvent;
  /** Optional circular number/stat */
  visualNumber?: CarouselVisualNumber;
  /** Optional summary takeaway box */
  takeaway?: CarouselTakeaway;

  generatedAt: string;
}

/** API response for GET /api/cards and POST /api/cards/generate */
export interface CardsResponse {
  ok: true;
  source: string | null;
  cards: ContentCard[];
}


// ------------------------------------------------------------------ reels

/**
 * One rendered vertical (9:16) reel cut from an uploaded video.
 * Files are served statically at /reels/<safeSource>/<file>.
 */
export interface ReelInfo {
  id: string;
  /** Uploaded file this reel was cut from */
  source: string;
  /** Clip window start in seconds */
  start: number;
  /** Clip window end in seconds */
  end: number;
  /** Duration in seconds */
  duration: number;
  /** Aliases for compatibility */
  startSec?: number;
  endSec?: number;
  durationSec?: number;
  /** Short hook/title shown over the reel */
  title: string;
  /** URL to the rendered mp4 (e.g. /reels/lecture_01/reel_001.mp4) */
  video: string;
  /** Compatibility alias for video URL */
  fileUrl?: string;
  /** URL to the generated SRT subtitle file */
  captions?: string;
  /** Text content/transcript for this reel window */
  transcript: string;
  /** Key bullet-point takeaways */
  takeaways: string[];
  /** 1-sentence summary */
  summary?: string;
  /** Per-clip rendering status */
  status: 'ready' | 'processing' | 'pending' | 'failed';
  error?: string;
  /** Subtitle cues with relative timestamps */
  cues?: Array<{ startSec: number; endSec: number; text: string }>;
  /** Render time */
  generatedAt: string;
}

/** Per-source reel set + generation job status. */
export interface ReelSet {
  source: string;
  status: 'completed' | 'processing' | 'generating' | 'ready' | 'idle' | 'failed';
  error?: string;
  videoAvailable: boolean;
  durationSec?: number;
  reels: ReelInfo[];
}

/** Response shape for GET /api/reels */
export interface ReelsResponse {
  ok: true;
  sources: ReelSet[];
}


